# Class 12: map / filter / reduce and NumPy matrices

In [33]:
from functools import reduce

import numpy.matlib 
import numpy as np

Important functions for building matrices:<br>
-map<br>
-filter<br>
-reduce<br>
-$\lambda$-calculus

In [23]:
def add_one(x):
    return x+1


vector = [645.6, 8765, 1089, 710, 6789, 591] # salaries
num = [3,2,-4,1,5]

In [26]:
#list(map[add_one, num])
list(map(lambda x: x**2, num))

[9, 4, 16, 1, 25]

In [6]:
(lambda x: x**2)(4)

16

In [11]:
list(filter(lambda x: x>1000, vector))

[8765, 1089, 6789]

In [27]:
reduce(lambda x,y: x+y, vector)

18589.6

Creating matrices:

In [34]:
matrix = [[1,5],[8,4],[7,2]]

a = np.array([[1,5],[8,4],[7,2]])
print(a)

[[1 5]
 [8 4]
 [7 2]]


In [48]:
a[0]

array([1, 5])

In [49]:
a[0][1]

5

In [46]:
a[:,:]

array([[1, 5],
       [8, 4],
       [7, 2]])

In [50]:
print(a.ndim)

2


In [51]:
# number of rows and columns
print(a.shape) 

(3, 2)


In [52]:
# number of values
print(a.size)


6


Explicit matrix typing:

In [54]:
b = np.array([[1,2],[4,7]], dtype=float)

In [55]:
print(b.dtype)

float64


In [57]:
# list converted into a matrix:
mt = [2.1,3.4,6.7,8.1,3.5,7.2]
b = np.array(mt).reshape(3,2)
b[:]

array([[2.1, 3.4],
       [6.7, 8.1],
       [3.5, 7.2]])

In [59]:
c = np.arange(0,15).reshape(5,3)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [69]:
h = np.resize(c, new_shape=(3,5))
print(h)

h.shape[0] # number of rows
h.shape[1] # number of columns

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


5

In [70]:
# matrix of zeros
b = np.zeros(shape=(2,4))
print(b)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [64]:
# matrix filled with any value
b = np.full(shape=(2,4), fill_value=2)
print(b)
b[0][2] = 4
b[:,:]

[[2 2 2 2]
 [2 2 2 2]]


array([[2, 2, 4, 2],
       [2, 2, 2, 2]])

In [72]:
b = np.array([[4.1,3.2]])
d = np.array([[7.8],[6.1],[5.4]])
d1 = np.append(a,d,axis=1)
d1[:,:]

array([[1. , 5. , 7.8],
       [8. , 4. , 6.1],
       [7. , 2. , 5.4]])